### ISSUE TITLE
show Documentation with Lösungsformular

### ISSUE THREAD

**Issue by jwaldmann** [klemens/openolat#56]
autolat shows Documentation with input window for problem configuration,
but this is missing with Lösungsformular.

This is how it is supposed to look: "solution is of type:	[Statement]"
https://autotool.imn.htwk-leipzig.de/cgi-bin/Trial.cgi?topic=Machine.Numerical.Goto

I consider this important: this is the one (often only) way for students to find out
about syntax and semantics of the solution language. Also, they are getting used to reading
type declarations and source code.

In autotool, I make considerable effort to build this documentation, cf. https://ghc.haskell.org/trac/ghc/ticket/10311

**Comment by klemens** [comment]
You are right, this is currently only shown for the configuration, but not for the solution.
I will add this with the next update (hopefully this weekend).

**Comment by klemens** [comment]
Fixed by d714b60500db5b04976d31e3bf94be7012a8756d:
![documentation](https://cloud.githubusercontent.com/assets/813206/7257871/f5ced174-e858-11e4-82d9-f1e0a7ca74d3.png)
