### ISSUE TITLE
Fehlerhafte Signatur bei CNF_SAT-Quiz-Aufgaben

### ISSUE THREAD

**Issue by klemens** [klemens/openolat#58]
Beim Abschicken einer Lösung für eine `CNF_SAT-Quiz`-Aufgabe wird nur die Fehlermeldung `error: invalid signature` zurückgegeben.

Scheinbar stimmt die Signatur für die `Instance` der Aufgabe, die vom `get_task_instance`-rpc geliefert wird, nicht mehr mit derjenigen überein, die beim Lösen zusammen mit der `Instance` an den Server geschickt wird.
Es ist im Moment jedoch noch unklar, ob die Aufgabeninstanz beim Speichern verändert wird oder die Berechnung der Signatur Probleme bereitet.

Interessant ist noch, dass der Fehler nur bei neueren Autotool-Versionen (oder bei Versionen auf dem neuen Server kernkraft.imn.htwk-leipzig.de?) auftritt, bei http://autolat.imn.htwk-leipzig.de/cgi-bin/autotool-0.2.0.cgi tritt der Fehler nicht auf.

Die Signaturberechnung findet hier statt: http://autolat.imn.htwk-leipzig.de/gitweb/?p=tool;f=server-implementation/src/Util/Sign.hs;hb=for-ghc-7.8

Gemeldet von @jwaldmann am 14.04.2015.

**Comment by klemens** [comment]
Der Regressionsbereich wird kleiner:
Letzte funktionierende Version: http://autolat.imn.htwk-leipzig.de/cgi-bin/autotool-0.2.1.cgi
Erste nicht funktionierende Version: http://autolat.imn.htwk-leipzig.de/cgi-bin/autotool-0.3.0.cgi

Gab es dazwischen irgendwelche API-Änderungen oder Änderungen bei der Signaturberechnung?

**Comment by jwaldmann** [comment]
Das (Änderungen) kann schon sein, aber das würde doch nur den Fall betreffen, daß die Signatur mit der alten autotool-Server-Version ausgerechnet, in Olat gespeichert, und mit der neuen autotool-Version geprüft wurde. Die Aufgabe funktioniert aber über meine Schnittstelle auch mit der aktuellen Server-Version ( https://autotool.imn.htwk-leipzig.de/cgi-bin/Trial.cgi?topic=CNF_SAT-Quiz ). 

Man müßte entweder bei  olat oder auf meinem Server die tatsächlich gesendeten Bytes mitschneiden. Wo geht das am einfachsten?

**Comment by klemens** [comment]
Ich hab die verschiedenen Serverversionen jeweils immer mit von der entsprechenden Version frisch generierten Aufgaben getestet.
Ich werd nachher mal versuchen, die Kommunikation mit Wireshark bei mir lokal mitzuschneiden. Da die Kommunikation ja nicht verschlüsselt wird, sollte das Problemlos funktionieren.

**Comment by klemens** [comment]
Mit Hilfe von Wireshark war der Fehler ganz leicht auffindbar:
Das Problem ist, dass der Aufgabentext, der mittels der Signatur validiert wird, bei den neuen Autotool-Versionen mit 3 Leerzeichen beginnt:
```
<string>   (  p ||
```
Die XML-RPC Bibliothek (Redstone) führt aber leider beim Empfangen ein Trim auf den Strings aus, womit dann schließlich
```
<string>(  p ||...
```
zum Server zurückgeschickt wird. Wenn ich im Debugger manuell die drei Leerzeichen vor dem Absenden einfüge, funktioniert alles problemlos.

Die RPC-Bibliothek hat leider auch keine Option, um das Trimmen auszuschalten und wird es wohl auch nicht so bald haben: http://sourceforge.net/p/xmlrpc/discussion/79303/thread/48033fab/ Ich muss die Bibliothek also forken.
Alternativ könnten wir uns natürlich auch darauf einigen, dass Whitespace am Anfang und Ende eines Strings bei der Signatur ignoriert wird. :wink:

**Comment by klemens** [comment]
Ich habe jetzt mal redstone geforkt und konnte das Problem damit umgehen: 79c7af1694658077006aa8eb2f3f2961cb7e6d41 und klemens/redstone@b588c0facaed4eae0f70264bcbac297f7e99602d
Allerdings halte ich es immer noch für besser, bei der Signaturberechnung whitespace einfach zu ignorieren.

Ich werde wohl morgen das Portal updaten, der workaround funktioniert allerdings nur bei neu angelegten Autotool-Knoten, da bei vorhandenen die getrimmten Aufgabenbeschreibungen möglicherweise schon in der Datenbank stehen und per UI auch nicht gelöscht werden können. (außer durch Löschen der Aufgabe)

**Comment by jwaldmann** [comment]
weitere Lösungsmöglichkeiten

1. andere Java-Xmlrpc-Bibliothek suchen, die den Whitespace in strings nicht kaputt macht
2. von Xml(rpc) umschalten auf ein besser definiertes Datenformat (JSON)
3. bei xmlrpc bleiben, aber strings werden kodiert (base64 oder ähnlich)

**Comment by klemens** [comment]
1. Als alternative XML-RPC-Libs kommen eigentlich nur https://github.com/vnesek/nmote-xr und https://github.com/timroes/aXMLRPC in Frage, alle anderen wurden schon seit Jahren nicht mehr aktualisiert. Letztere sieht auf den ersten Blick sympathischer aus, müsste ich mir aber nochmal genauer anschauen.
2. Redstone benutzt sax als Parser, allerdings wird der whitespace nicht vom Parser gelöscht, sondern anschließend von redstone selbst, das würde also nichts ändern.
3. Da gäbe es dann http://www.jsonrpc.org/specification. Sieht auf den ersten Blick recht simpel aus, gibt u.a. auch eine aktuelle [Haskell-Implementierung](http://hackage.haskell.org/package/json-rpc-server) und mehrere in Java.
4. Finde ich jetzt nicht so toll, denn das ist ja wieder nur ein Workaround. Außerdem bläht es die Nachrichten auf und macht das Debuggen umständlicher.

Für das Update nachher bleib ich jetzt erstmal bei meinem redstone-Fork, grundsätzlich fände ich einen Umstieg auf JSON jedoch schon sinnvoll.

**Comment by jwaldmann** [comment]
OK. 

json-rpc sieht gut aus, kann man serverseitig sicher das benutzen: hackage.haskell.org/package/json-rpc-server

**Comment by klemens** [comment]
So, das Update ist eingespielt: Neue CNF_SAT-Quiz-Aufgaben funktionieren nun problemlos.

Für die zukünftig mögliche Umstellung auf JSON-RPC hab ich ein neues Ticket angelegt: #59
