### ISSUE TITLE
falsche Beschriftung "Beginn Bewertungszeitraum" in Kurseditor Autotool-Aufgabe Bewertungseigenschaften

### ISSUE THREAD

**Issue by jwaldmann** [klemens/openolat#60]
bei Ansicht einer bereits bestehenden Autotool-Aufgabe im Kurseditor sehe ich zweimal
"Beginn des Bewertungszeitraums", aber beim zweiten Mal sollte "Ende des ..." stehen.

**Comment by klemens** [comment]
Bug gehoben im verlinkten commit.
