### ISSUE TITLE
Kurseditor Autotool-Struktur: Aufgabe einfügen: Einfügeposition ist überraschend

### ISSUE THREAD

**Issue by jwaldmann** [klemens/openolat#61]
Ist-Zustand: neue Aufgabe wird neben (und zwar direkt danach) dem gewählten Element (Aufgabe) eingefügt.

Erwartet: gewählt wird ein Verzeichnis, Aufgabe wird darin eingefügt, am Ende (bzw. Sortierung
nach Beginn oder Ende Bewertungszeitraum)

Begründung: (Analogie) wenn ich eine neue Datei editieren will, dann sage ich "emacs foo.text"
im aktuellen Verzeichnis. Ich sage nicht "emacs bar.text", auch wenn die neue Datei schließlich
hinter der bestehenden "bar.text" angezeigt wird.

**Comment by klemens** [comment]
Die Analogie verwirrt mich jetzt zwar gerade eher, als dass sie hilft :wink:, aber das Problem ist mir bekannt.

Ich seh mal, ob ich da was machen kann; ein Problem könnte jedoch werden, dass die Baumstruktur nicht von autolat direkt, sondern von OO verwaltet wird.

**Comment by klemens** [comment]
Wie vermutet ist eine Anpassung der Einfügelogik nicht direkt möglich. Allerdings scheint das Drag&Drop zum Verschieben der Knoten in der aktuellen OpenOLAT-Version verbessert worden zu sein.
