### ISSUE TITLE
Kurseditor autotool-Aufgabe: nervige pop-ups beim Speichern

### ISSUE THREAD

**Issue by jwaldmann** [klemens/openolat#62]
Nach jeder Speicher-Aktion erscheint ein Popup mit der Nachricht, daß etwas gespeichert wurde. Das nervt. Auf kleinen Bildschirmen nimmt es wichtigen Platz weg. Kann man diese Popups bitte grundsätzlich weglassen. Bei welchen Anwendungsfällen werden die gebraucht?

**Comment by klemens** [comment]
Ich hab nun die nervigsten Meldungen im verlinkten Commit entfernt. Beim Auswählen einer existierenden Aufgabenkonfiguration und beim Import werden weiterhin Meldungen angezeigt.
