### ISSUE TITLE
Configuration of mathjax

### ISSUE THREAD

**Issue by johnny-bui** [klemens/openolat#68]
Can I configuration the URL of MathJax via URL like this: ?config=TeX-AMS-MML_HTMLorMML? As the version 11.3 I can only configure where to load MathJax, but not how should a browser load mathjax.

**Comment by klemens** [comment]
This is not the official OpenOLAT bug tracker (or the official repo), you should ask on the official mailing list: https://groups.google.com/forum/#!forum/openolat
